[FIX] multiples little issues in bids_mcflirt wrapper

diff --git a/mcflirt/bids_mcflirt b/mcflirt/bids_mcflirt
--- a/mcflirt/bids_mcflirt
+++ b/mcflirt/bids_mcflirt
@@ -17,10 +17,10 @@ This program has two mandatory arguments:
   * OUTPUTDIR is any output directory of your choice, and will be created
     as needed. Under it, one subdirectories will be created:
       mc_output/
-      
+
     and under each, there will be a subdirectory for each BIDS subject,
     either as "sub-1234" or "sub-1234_ses-abcd" (depending on whether or
-    not the subject contains sessions). 
+    not the subject contains sessions).
 
 The rest of the options are ANY parameters supported by mcflirt, -i, -o. Supplying these options will
 result in unpredicatble results, as it will confuse the internal
@@ -50,25 +50,26 @@ shift;shift
 test -d "$bidsdataset"                          || die "First argument must be a BIDS directory."
 test -e "$bidsdataset/dataset_description.json" || die "BIDS dataset missing JSON description."
 
-# Prepare output
-mkdir -p "$deriv_out" || die "Cannot create output dir"
-
 echo "$0 $VERSION starting at" `date`
-
 
 count_attempt=0
 count_success=0
 
+# Prepare output
+origdir=$(pwd)
+mkdir -p "$deriv_out" || die "Cannot create output dir"
+outputdir="$deriv_out/mc_output"
+mkdir -p "$outputdir" || die "Cannot create output dir for mcflirt ?!?"
+cd $outputdir
 
 # Scan subjects
-for subjdir in "$bidsdataset"/sub-* ; do
+for subjdir in "$origdir/$bidsdataset"/sub-* ; do
   test -d "$subjdir" || continue # ignore any non-dir that happens ot start with sub-
   subject=$(basename $subjdir)
 
   # Extract list of sessions, or just '.' if there are none
   sesslist=$(ls -1f $subjdir | grep '^ses-' | sort)
   test -z "$sesslist" && sesslist="none"
-  count_attempt=$(( $count_attempt + 1 ))
   # Loop through sessions; if there are no sessions, we have a fake
   # one called 'none'.
   for session in $sesslist ; do
@@ -86,12 +87,11 @@ for subjdir in "$bidsdataset"/sub-* ; do
     echo "======================================================="
     echo " SUBJECT $subject SESSION $session"
     echo "======================================================="
-    
+
     # Find the list of asl files
     # files we also need.
     fmrifiles=${subdata}/func/${sub_sess}*bold.nii*
-    
-    count_attempt=$(( $count_attempt + 1 ))
+
     for fmrifile in $fmrifiles ; do
 
       if ! test -f "$fmrifile" ; then
@@ -101,7 +101,6 @@ for subjdir in "$bidsdataset"/sub-* ; do
 
       # "BIDS/sub-1/{ses}/perf/{sub}_{ses}_{task}_{run}"
       perf_prefix=$(echo $fmrifile     | sed -e 's#_bold.nii.*##')
-      
 
       # Variable to show sub, ses, task, run etc etc
       full_context=$(basename $perf_prefix)
@@ -110,21 +109,22 @@ for subjdir in "$bidsdataset"/sub-* ; do
       echo "-------------------------------------------------------"
       echo " MCFLIRT, Context=$full_context"
       echo "-------------------------------------------------------"
-      mkdir -p "$deriv_out/mc_out" || die "Cannot create output dir for mcflirt ?!?"
-      oasl_out="$deriv_out/mc_out/$full_context"
-      oasl_log="$deriv_out/mc_out/$full_context.log"
+      oasl_out="$full_context"
+      oasl_log="$full_context.log"
 
       if test -d "$oasl_out" ; then
         echo " -> re-using mcflirt output in $oasl_out"
         echo " -> (if this output is corrupt, consider deleting it)"
         oasl_status=0
       else
-        $MCFLIRT_EXE                 \
-          -in "$fmrifile"            \
-          -o "$oasl_out"             \
-          "$@"                       \
-          2>&1 | tee "$oasl_log"
-        oasl_status=$?
+        count_attempt=$(( $count_attempt + 1 ))
+        echo " -> running mcflirt"
+        command_line="$MCFLIRT_EXE -in $fmrifile -o $oasl_out $@"
+        echo " -> command line:"
+        echo "$command_line"
+        $command_line 2>&1 | tee "$oasl_log"
+        oasl_status=${PIPESTATUS[0]}
+        echo " -> mcflirt finished with status $oasl_status"
       fi
 
       if test $oasl_status -ne 0 ; then
@@ -134,15 +134,6 @@ for subjdir in "$bidsdataset"/sub-* ; do
         continue
       fi
 
-     if [[ $count_attempt == "0" ]];then
-       exit 2
-     elif [[ $count_attempt != $count_success ]];then
-       exit 1
-     elif [$count_attempt -eq $count_success] && [$count_attempt -gt 0];then
-       exit 0
-     fi
-     
-
     done # BOLD image file loop
 
   done # sessions loop
@@ -150,4 +141,13 @@ for subjdir in "$bidsdataset"/sub-* ; do
 done # subjects loop
 
 echo "$0 ending at" `date`
+
+if [[ $count_attempt == "0" ]];then
+  exit 2
+elif [[ $count_attempt != $count_success ]];then
+  exit 1
+elif [[ $count_attempt -eq $count_success ]] && [[ $count_attempt -gt 0 ]];then
+  exit 0
+fi
+
 
